import clsx from 'clsx';
import type { Metadata } from 'next';
import './globals.css';
import { Inter } from 'next/font/google';
import type { ReactNode } from 'react';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Cover Letter Generator',
  description: 'Generate a cover letter for your job application using AI',
};

const RootLayout = ({ children }: { children: Readonly<ReactNode> }) => {
  return (
    <html lang="en">
    <body
      className={clsx([
        inter.className,
        'bg-background-primary',
        'text-white',
      ])}
    >
    {children}
    </body>
    </html>
  );
};

export default RootLayout;

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
//
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
//
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
//
// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//     <body
//       className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//     >
//     {children}
//     </body>
//     </html>
//   );
// }
